
CREATE TABLE INMOBIX.PROPERTY_AUDIT (
    AUDIT_ID           BIGSERIAL,
    OPERATION          CHAR(1)   NOT NULL,                               
    -- I=Insert, U=Update, D=Delete
    AUDIT_TIMESTAMP    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    AUDIT_USER         TEXT        DEFAULT CURRENT_USER NOT NULL,
    AUDIT_SESSION_USER TEXT        DEFAULT SESSION_USER NOT NULL,

    -- Valores ANTES del cambio (para UPDATE y DELETE)
    OLD_ID                VARCHAR(4),
    OLD_ADDRESS           VARCHAR(50),
    OLD_ESTIMATED_WIDTH   INTEGER,
    OLD_ESTIMATED_DEPTH   INTEGER,
    OLD_BOUNDARIES        VARCHAR(500),
    OLD_STRATUM           VARCHAR(4),
    OLD_IS_ACTIVE         CHAR(1),
    OLD_CTY_DPT_ID        VARCHAR(4),
    OLD_CTY_ID            VARCHAR(4),
    OLD_CET_NDOCUMENT     VARCHAR(10),

    -- Valores DESPUÉS del cambio (para INSERT y UPDATE)
    NEW_ID                VARCHAR(4),
    NEW_ADDRESS           VARCHAR(50),
    NEW_ESTIMATED_WIDTH   INTEGER,
    NEW_ESTIMATED_DEPTH   INTEGER,
    NEW_BOUNDARIES        VARCHAR(500),
    NEW_STRATUM           VARCHAR(4),
    NEW_IS_ACTIVE         CHAR(1),
    NEW_CTY_DPT_ID        VARCHAR(4),
    NEW_CTY_ID            VARCHAR(4),
    NEW_CET_NDOCUMENT     VARCHAR(10),

    CONSTRAINT PK_PROPERTY_AUDIT PRIMARY KEY (AUDIT_ID),
    CONSTRAINT NN_PROPERTY_AUDIT_OPERATION CHECK (OPERATION IS NOT NULL),
    CONSTRAINT CK_PROPERTY_AUDIT_OPERATION CHECK (OPERATION IN ('I','U','D'))
);

-- Índices para rendimiento en consultas de auditoría
CREATE INDEX IDX_PROPERTY_AUDIT_TIMESTAMP ON INMOBIX.PROPERTY_AUDIT(AUDIT_TIMESTAMP DESC);
CREATE INDEX IDX_PROPERTY_AUDIT_PROPERTY   ON INMOBIX.PROPERTY_AUDIT(NEW_ID, OLD_ID);
```

# 2. Trigger + Función que llena automáticamente la auditoría

```sql
-- =============================================
-- Trigger y función de auditoría para PROPERTY
-- =============================================

CREATE OR REPLACE FUNCTION INMOBIX.fn_audit_property() 
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO INMOBIX.PROPERTY_AUDIT (
            OPERATION,
            NEW_ID, NEW_ADDRESS, NEW_ESTIMATED_WIDTH, NEW_ESTIMATED_DEPTH,
            NEW_BOUNDARIES, NEW_STRATUM, NEW_IS_ACTIVE,
            NEW_CTY_DPT_ID, NEW_CTY_ID, NEW_CET_NDOCUMENT
        ) VALUES (
            'I',
            NEW.ID, NEW.ADDRESS, NEW.ESTIMATED_WIDTH, NEW.ESTIMATED_DEPTH,
            NEW.BOUNDARIES, NEW.STRATUM, NEW.IS_ACTIVE,
            NEW.CTY_DPT_ID, NEW.CTY_ID, NEW.CET_NDOCUMENT
        );

    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO INMOBIX.PROPERTY_AUDIT (
            OPERATION,
            OLD_ID, OLD_ADDRESS, OLD_ESTIMATED_WIDTH, OLD_ESTIMATED_DEPTH,
            OLD_BOUNDARIES, OLD_STRATUM, OLD_IS_ACTIVE,
            OLD_CTY_DPT_ID, OLD_CTY_ID, OLD_CET_NDOCUMENT,
            NEW_ID, NEW_ADDRESS, NEW_ESTIMATED_WIDTH, NEW_ESTIMATED_DEPTH,
            NEW_BOUNDARIES, NEW_STRATUM, NEW_IS_ACTIVE,
            NEW_CTY_DPT_ID, NEW_CTY_ID, NEW_CET_NDOCUMENT
        ) VALUES (
            'U',
            OLD.ID, OLD.ADDRESS, OLD.ESTIMATED_WIDTH, OLD.ESTIMATED_DEPTH,
            OLD.BOUNDARIES, OLD.STRATUM, OLD.IS_ACTIVE,
            OLD.CTY_DPT_ID, OLD.CTY_ID, OLD.CET_NDOCUMENT,
            NEW.ID, NEW.ADDRESS, NEW.ESTIMATED_WIDTH, NEW.ESTIMATED_DEPTH,
            NEW.BOUNDARIES, NEW.STRATUM, NEW.IS_ACTIVE,
            NEW.CTY_DPT_ID, NEW.CTY_ID, NEW.CET_NDOCUMENT
        );

    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO INMOBIX.PROPERTY_AUDIT (
            OPERATION,
            OLD_ID, OLD_ADDRESS, OLD_ESTIMATED_WIDTH, OLD_ESTIMATED_DEPTH,
            OLD_BOUNDARIES, OLD_STRATUM, OLD_IS_ACTIVE,
            OLD_CTY_DPT_ID, OLD_CTY_ID, OLD_CET_NDOCUMENT
        ) VALUES (
            'D',
            OLD.ID, OLD.ADDRESS, OLD.ESTIMATED_WIDTH, OLD.ESTIMATED_DEPTH,
            OLD.BOUNDARIES, OLD.STRATUM, OLD.IS_ACTIVE,
            OLD.CTY_DPT_ID, OLD.CTY_ID, OLD.CET_NDOCUMENT
        );
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger
CREATE TRIGGER trg_audit_property
    AFTER INSERT OR UPDATE OR DELETE ON INMOBIX.PROPERTY
    FOR EACH ROW
    EXECUTE FUNCTION INMOBIX.fn_audit_property();
