-- =============================================
-- FUNCIÓN Y TRIGGER DE AUDITORÍA PARA PROPERTY
-- =============================================

CREATE OR REPLACE FUNCTION INMOBIX.fn_audit_property()
RETURNS TRIGGER AS $$
BEGIN

    -- INSERT
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO INMOBIX.PROPERTY_AUDIT (
            OPERATION,
            NEW_ID, NEW_ADDRESS, NEW_ESTIMATED_WIDTH, NEW_ESTIMATED_DEPTH,
            NEW_BOUNDARIES, NEW_STRATUM, NEW_IS_ACTIVE,
            NEW_CTY_DPT_ID, NEW_CTY_ID, NEW_CET_NDOCUMENT
        )
        VALUES (
            'I',
            NEW.ID, NEW.ADDRESS, NEW.ESTIMATED_WIDTH, NEW.ESTIMATED_DEPTH,
            NEW.BOUNDARIES, NEW.STRATUM, NEW.IS_ACTIVE,
            NEW.CTY_DPT_ID, NEW.CTY_ID, NEW.CET_NDOCUMENT
        );

    -- UPDATE
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO INMOBIX.PROPERTY_AUDIT (
            OPERATION,
            OLD_ID, OLD_ADDRESS, OLD_ESTIMATED_WIDTH, OLD_ESTIMATED_DEPTH,
            OLD_BOUNDARIES, OLD_STRATUM, OLD_IS_ACTIVE,
            OLD_CTY_DPT_ID, OLD_CTY_ID, OLD_CET_NDOCUMENT,
            NEW_ID, NEW_ADDRESS, NEW_ESTIMATED_WIDTH, NEW_ESTIMATED_DEPTH,
            NEW_BOUNDARIES, NEW_STRATUM, NEW_IS_ACTIVE,
            NEW_CTY_DPT_ID, NEW_CTY_ID, NEW_CET_NDOCUMENT
        )
        VALUES (
            'U',
            OLD.ID, OLD.ADDRESS, OLD.ESTIMATED_WIDTH, OLD.ESTIMATED_DEPTH,
            OLD.BOUNDARIES, OLD.STRATUM, OLD.IS_ACTIVE,
            OLD.CTY_DPT_ID, OLD.CTY_ID, OLD.CET_NDOCUMENT,
            NEW.ID, NEW.ADDRESS, NEW.ESTIMATED_WIDTH, NEW.ESTIMATED_DEPTH,
            NEW.BOUNDARIES, NEW.STRATUM, NEW.IS_ACTIVE,
            NEW.CTY_DPT_ID, NEW.CTY_ID, NEW.CET_NDOCUMENT
        );

    -- DELETE
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO INMOBIX.PROPERTY_AUDIT (
            OPERATION,
            OLD_ID, OLD_ADDRESS, OLD_ESTIMATED_WIDTH, OLD_ESTIMATED_DEPTH,
            OLD_BOUNDARIES, OLD_STRATUM, OLD_IS_ACTIVE,
            OLD_CTY_DPT_ID, OLD_CTY_ID, OLD_CET_NDOCUMENT
        )
        VALUES (
            'D',
            OLD.ID, OLD.ADDRESS, OLD.ESTIMATED_WIDTH, OLD.ESTIMATED_DEPTH,
            OLD.BOUNDARIES, OLD.STRATUM, OLD.IS_ACTIVE,
            OLD.CTY_DPT_ID, OLD.CTY_ID, OLD.CET_NDOCUMENT
        );
        RETURN OLD;
    END IF;

    RETURN NULL; -- no importa para AFTER trigger
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear el trigger
CREATE TRIGGER trg_audit_property
    AFTER INSERT OR UPDATE OR DELETE ON INMOBIX.PROPERTY
    FOR EACH ROW
    EXECUTE FUNCTION INMOBIX.fn_audit_property();
