-- =============================================
-- ESQUEMA INMOBIX - MODELO
-- =============================================

-- Crear el esquema si no existe
CREATE SCHEMA IF NOT EXISTS INMOBIX;

-- Tabla INMOBIX.DEPARTAMENT
CREATE TABLE INMOBIX.DEPARTAMENT (
    ID VARCHAR(4),
    NAME VARCHAR(30),
    CONSTRAINT PK_DEPARTAMENT PRIMARY KEY (ID),
    CONSTRAINT NN_DEPARTAMENT_NAME CHECK (NAME IS NOT NULL)
);

-- Tabla INMOBIX.CITY
CREATE TABLE INMOBIX.CITY (
    ID VARCHAR(4),
    NAME VARCHAR(30),
    DPT_ID VARCHAR(4),
    CONSTRAINT PK_CITY PRIMARY KEY (DPT_ID, ID),
    CONSTRAINT NN_CITY_NAME CHECK (NAME IS NOT NULL),
    CONSTRAINT NN_CITY_DPT_ID CHECK (DPT_ID IS NOT NULL),
    CONSTRAINT FK_CITY_DEPARTAMENT FOREIGN KEY (DPT_ID) REFERENCES INMOBIX.DEPARTAMENT(ID)
);

-- Tabla INMOBIX.CLIENT
CREATE TABLE INMOBIX.CLIENT (
    NUMBERDOCUMENT VARCHAR(10),
    GRADE_DESCRIPTION VARCHAR(500),
    FIRST_NAME VARCHAR(50),
    SECOND_NAME VARCHAR(50),
    FIRST_LASTNAME VARCHAR(50),
    SECOND_LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(15),
    BIRTHDATE DATE,
    CONSTRAINT PK_CLIENT PRIMARY KEY (NUMBERDOCUMENT),
    CONSTRAINT NN_CLIENT_GRADE_DESCRIPTION CHECK (GRADE_DESCRIPTION IS NOT NULL),
    CONSTRAINT NN_CLIENT_FIRST_NAME CHECK (FIRST_NAME IS NOT NULL),
    CONSTRAINT NN_CLIENT_FIRST_LASTNAME CHECK (FIRST_LASTNAME IS NOT NULL),
    CONSTRAINT NN_CLIENT_EMAIL CHECK (EMAIL IS NOT NULL),
    CONSTRAINT NN_CLIENT_PHONE CHECK (PHONE IS NOT NULL),
    CONSTRAINT NN_CLIENT_BIRTHDATE CHECK (BIRTHDATE IS NOT NULL),
    CONSTRAINT UK_CLIENT_EMAIL UNIQUE (LOWER(EMAIL))
);

-- Tabla INMOBIX.DOCUMENTTYPE
CREATE TABLE INMOBIX.DOCUMENTTYPE (
    CET_PFK VARCHAR(10),
    ABBR VARCHAR(2),
    NAME VARCHAR(30),
    CONSTRAINT PK_DOCUMENTTYPE PRIMARY KEY (CET_PFK),
    CONSTRAINT NN_DOCUMENTTYPE_ABBR CHECK (ABBR IS NOT NULL),
    CONSTRAINT NN_DOCUMENTTYPE_NAME CHECK (NAME IS NOT NULL),
    CONSTRAINT FK_DOCUMENTTYPE_CLIENT FOREIGN KEY (CET_PFK) REFERENCES INMOBIX.CLIENT(NUMBERDOCUMENT)
);

-- Tabla INMOBIX.EMPLOYEE
CREATE TABLE INMOBIX.EMPLOYEE (
    ID VARCHAR(4),
    NUMBER_DOCUMENT VARCHAR(10),
    POSITION VARCHAR(30),
    FIRST_NAME VARCHAR(15),
    SECOND_NAME VARCHAR(15),
    FIRST_LAST_NAME VARCHAR(15),
    SECOND_LAST_NAME VARCHAR(15),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(10),
    EPE_ID_BOSS VARCHAR(4),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    CONSTRAINT NN_EMPLOYEE_NUMBER_DOCUMENT CHECK (NUMBER_DOCUMENT IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_POSITION CHECK (POSITION IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_FIRST_NAME CHECK (FIRST_NAME IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_SECOND_NAME CHECK (SECOND_NAME IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_FIRST_LAST_NAME CHECK (FIRST_LAST_NAME IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_SECOND_LAST_NAME CHECK (SECOND_LAST_NAME IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_EMAIL CHECK (EMAIL IS NOT NULL),
    CONSTRAINT NN_EMPLOYEE_BOSS CHECK (EPE_ID_BOSS IS NOT NULL),
    CONSTRAINT FK_EMPLOYEE_BOSS FOREIGN KEY (EPE_ID_BOSS) REFERENCES INMOBIX.EMPLOYEE(ID),
    CONSTRAINT FK_EMPLOYEE_DOCTYPE FOREIGN KEY (NUMBER_DOCUMENT) REFERENCES INMOBIX.DOCUMENTTYPE(CET_PFK)
);

-- Tabla INMOBIX.PROPERTY
CREATE TABLE INMOBIX.PROPERTY (
    ID VARCHAR(4),
    ADDRESS VARCHAR(50),
    ESTIMATED_WIDTH INTEGER,
    ESTIMATED_DEPTH INTEGER,
    BOUNDARIES VARCHAR(500),
    STRATUM VARCHAR(4),
    IS_ACTIVE CHAR(1),
    CTY_DPT_ID VARCHAR(4),
    CTY_ID VARCHAR(4),
    CET_NDOCUMENT VARCHAR(10),
    CONSTRAINT PK_PROPERTY PRIMARY KEY (ID),
    CONSTRAINT NN_PROPERTY_ADDRESS CHECK (ADDRESS IS NOT NULL),
    CONSTRAINT NN_PROPERTY_ESTIMATED_WIDTH CHECK (ESTIMATED_WIDTH IS NOT NULL),
    CONSTRAINT NN_PROPERTY_BOUNDARIES CHECK (BOUNDARIES IS NOT NULL),
    CONSTRAINT NN_PROPERTY_STRATUM CHECK (STRATUM IS NOT NULL),
    CONSTRAINT NN_PROPERTY_IS_ACTIVE CHECK (IS_ACTIVE IS NOT NULL),
    CONSTRAINT NN_PROPERTY_CTY_DPT_ID CHECK (CTY_DPT_ID IS NOT NULL),
    CONSTRAINT NN_PROPERTY_CTY_ID CHECK (CTY_ID IS NOT NULL),
    CONSTRAINT NN_PROPERTY_CET_NDOCUMENT CHECK (CET_NDOCUMENT IS NOT NULL),
    CONSTRAINT FK_PROPERTY_CITY FOREIGN KEY (CTY_DPT_ID, CTY_ID) REFERENCES INMOBIX.CITY(DPT_ID, ID),
    CONSTRAINT FK_PROPERTY_CLIENT FOREIGN KEY (CET_NDOCUMENT) REFERENCES INMOBIX.CLIENT(NUMBERDOCUMENT),
    CONSTRAINT CK_PROPERTY_IS_ACTIVE CHECK (IS_ACTIVE IN ('1','0'))
);

-- Tabla INMOBIX.HOME
CREATE TABLE INMOBIX.HOME (
    ID_PPY VARCHAR(4),
    TOTALBATHROOMS INTEGER,
    TOTALBEDROOMS INTEGER,
    PARKINGSIZE INTEGER,
    CONSTRAINT PK_HOME PRIMARY KEY (ID_PPY),
    CONSTRAINT NN_HOME_TOTALBATHROOMS CHECK (TOTALBATHROOMS IS NOT NULL),
    CONSTRAINT NN_HOME_TOTALBEDROOMS CHECK (TOTALBEDROOMS IS NOT NULL),
    CONSTRAINT NN_HOME_PARKINGSIZE CHECK (PARKINGSIZE IS NOT NULL),
    CONSTRAINT FK_HOME_PROPERTY FOREIGN KEY (ID_PPY) REFERENCES INMOBIX.PROPERTY(ID) ON DELETE CASCADE
);

-- Tabla INMOBIX.COMMERCIAL
CREATE TABLE INMOBIX.COMMERCIAL (
    ID_PPY VARCHAR(4),
    ISWAREHOUSE CHAR(1),
    CONSTRAINT PK_COMMERCIAL PRIMARY KEY (ID_PPY),
    CONSTRAINT NN_COMMERCIAL_ISWAREHOUSE CHECK (ISWAREHOUSE IS NOT NULL),
    CONSTRAINT CK_COMMERCIAL_ISWAREHOUSE CHECK (ISWAREHOUSE IN ('1','0')),
    CONSTRAINT FK_COMMERCIAL_PROPERTY FOREIGN KEY (ID_PPY) REFERENCES INMOBIX.PROPERTY(ID) ON DELETE CASCADE
);

-- Tabla INMOBIX.CONTRACT
CREATE TABLE INMOBIX.CONTRACT (
    ID VARCHAR(15),
    PPY_ID VARCHAR(4),
    EPE_ID_BOSS VARCHAR(4),
    CET_NDOCUMENT VARCHAR(10),
    STATUS CHAR(1),
    "DATE" DATE,
    CONSTRAINT PK_CONTRACT PRIMARY KEY (ID),
    CONSTRAINT NN_CONTRACT_PPY_ID CHECK (PPY_ID IS NOT NULL),
    CONSTRAINT NN_CONTRACT_EPE_ID_BOSS CHECK (EPE_ID_BOSS IS NOT NULL),
    CONSTRAINT NN_CONTRACT_CET_NDOCUMENT CHECK (CET_NDOCUMENT IS NOT NULL),
    CONSTRAINT NN_CONTRACT_STATUS CHECK (STATUS IS NOT NULL),
    CONSTRAINT NN_CONTRACT_DATE CHECK ("DATE" IS NOT NULL),
    CONSTRAINT FK_CONTRACT_PROPERTY FOREIGN KEY (PPY_ID) REFERENCES INMOBIX.PROPERTY(ID),
    CONSTRAINT FK_CONTRACT_EMPLOYEE FOREIGN KEY (EPE_ID_BOSS) REFERENCES INMOBIX.EMPLOYEE(ID),
    CONSTRAINT FK_CONTRACT_CLIENT FOREIGN KEY (CET_NDOCUMENT) REFERENCES INMOBIX.CLIENT(NUMBERDOCUMENT)
);

-- Tabla INMOBIX.LEASECONTRACT
CREATE TABLE INMOBIX.LEASECONTRACT (
    ID_CTT VARCHAR(15),
    ISCOMMERCIAL CHAR(1),
    AMOUNT NUMERIC(14,2),
    ENDDATE DATE,
    MOVEINDATE DATE,
    INITIALDEPOSIT NUMERIC(14,2),
    INCREMENTRULE TEXT,
    PENALTYMONTHS INTEGER,
    NOTICEPERIODDAYS INTEGER,
    LATEINTERESTRATE INTEGER,
    CONSTRAINT PK_LEASECONTRACT PRIMARY KEY (ID_CTT),
    CONSTRAINT NN_LEASECONTRACT_ISCOMMERCIAL CHECK (ISCOMMERCIAL IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_AMOUNT CHECK (AMOUNT IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_MOVEINDATE CHECK (MOVEINDATE IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_INITIALDEPOSIT CHECK (INITIALDEPOSIT IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_INCREMENTRULE CHECK (INCREMENTRULE IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_PENALTYMONTHS CHECK (PENALTYMONTHS IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_NOTICEPERIODDAYS CHECK (NOTICEPERIODDAYS IS NOT NULL),
    CONSTRAINT NN_LEASECONTRACT_LATEINTERESTRATE CHECK (LATEINTERESTRATE IS NOT NULL),
    CONSTRAINT CK_LEASECONTRACT_ISCOMMERCIAL CHECK (ISCOMMERCIAL IN ('1','0')),
    CONSTRAINT FK_LEASECONTRACT_CONTRACT FOREIGN KEY (ID_CTT) REFERENCES INMOBIX.CONTRACT(ID) ON DELETE CASCADE
);

-- Tabla INMOBIX.SALECONTRACT (sin FK a PAYMENT todavía)
CREATE TABLE INMOBIX.SALECONTRACT (
    CONTRACT_ID VARCHAR(15),
    AMOUNT NUMERIC(16,2),
    COMMISSION NUMERIC(16,2),
    COMMISSIONPERCENTAGE INTEGER,
    PAYMENT_ID VARCHAR(10),
    ISEXCLUSIVE CHAR(1),
    INCLUDESCOMMISSIONPENALTY CHAR(1),
    EXCLUSIVITYENDDATE DATE,
    EXCLUSIVITYPENALTYAMOUNT NUMERIC(16,2),
    CONSTRAINT PK_SALECONTRACT PRIMARY KEY (CONTRACT_ID),
    CONSTRAINT NN_SALECONTRACT_AMOUNT CHECK (AMOUNT IS NOT NULL),
    CONSTRAINT NN_SALECONTRACT_COMMISSION CHECK (COMMISSION IS NOT NULL),
    CONSTRAINT NN_SALECONTRACT_COMMISSIONPERCENTAGE CHECK (COMMISSIONPERCENTAGE IS NOT NULL),
    CONSTRAINT NN_SALECONTRACT_PAYMENT_ID CHECK (PAYMENT_ID IS NOT NULL),
    CONSTRAINT NN_SALECONTRACT_ISEXCLUSIVE CHECK (ISEXCLUSIVE IS NOT NULL),
    CONSTRAINT CK_SALECONTRACT_ISEXCLUSIVE CHECK (ISEXCLUSIVE IN ('1','0')),
    CONSTRAINT FK_SALECONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES INMOBIX.CONTRACT(ID) ON DELETE CASCADE
);

-- Tabla INMOBIX.PAYMENT
CREATE TABLE INMOBIX.PAYMENT (
    ID VARCHAR(10),
    "DATE" DATE,
    MONTH CHAR(2),
    YEAR CHAR(4),
    AMOUNT NUMERIC(14,2),
    LCT_ID_CTT VARCHAR(15),
    SCT_CTT_ID VARCHAR(15),
    CONSTRAINT PK_PAYMENT PRIMARY KEY (ID),
    CONSTRAINT NN_PAYMENT_DATE CHECK ("DATE" IS NOT NULL),
    CONSTRAINT NN_PAYMENT_MONTH CHECK (MONTH IS NOT NULL),
    CONSTRAINT NN_PAYMENT_AMOUNT CHECK (AMOUNT IS NOT NULL)
    -- LCT_ID_CTT y SCT_CTT_ID pueden ser NULL según el tipo de pago
);

-- FKs de PAYMENT
ALTER TABLE INMOBIX.PAYMENT
    ADD CONSTRAINT FK_PAYMENT_LEASECONTRACT FOREIGN KEY (LCT_ID_CTT) 
    REFERENCES INMOBIX.LEASECONTRACT(ID_CTT);

ALTER TABLE INMOBIX.PAYMENT
    ADD CONSTRAINT FK_PAYMENT_SALECONTRACT FOREIGN KEY (SCT_CTT_ID) 
    REFERENCES INMOBIX.SALECONTRACT(CONTRACT_ID);

-- FK de SALECONTRACT → PAYMENT (ahora ya existe la tabla)
ALTER TABLE INMOBIX.SALECONTRACT
    ADD CONSTRAINT FK_SALECONTRACT_PAYMENT FOREIGN KEY (PAYMENT_ID) 
    REFERENCES INMOBIX.PAYMENT(ID);

-- =============================================
-- FIN DEL ESQUEMA INMOBIX
